// ppg.sv  –  Partial Product Generator (multi-precision Booth-radix-4)
//
// The four element widths (8/16/32/64) are generated by a single `generate`
// loop, parameterised by m ∈ {0,1,2,3}  →  W_M = 8 << m.
// Reduces ~275-line file to ~100 lines with identical logic.

module ppg #(
    parameter WIDTH = 64
)
(
    input  [WIDTH-1:0]   multiplicand,
    input  [1:0]         vector_mode,   // 0:8b  1:16b  2:32b  3:64b
    input  [31:0]        index,
    input                is_unsigned,
    input  [1:0]         hot_ones,      // {seln2, seln1} from previous PP
    input                selze,         // select  0
    input                selp1,         // select +A
    input                selp2,         // select +2A
    input                seln1,         // select −A
    input                seln2,         // select −2A
    output [2*WIDTH-1:0] partial_product
);


    localparam BW = 2*WIDTH + 4;   // bundle container width

    // ── Index decomposition ──────────────────────────────────────────────────
    wire [31:0] div = index >> (vector_mode + 2);
    wire [31:0] rem = index &  ((1 << (vector_mode + 2)) - 1);

    wire is_first = (rem == 0);
    wire is_last  = (rem == ((1 << (vector_mode + 2)) - 1));
    wire [1:0] hotest_ones = (rem == 0) ? 2'b00 : hot_ones;

    wire [WIDTH-1:0] selected_multiplicand = multiplicand >> (div << (vector_mode + 3));

    // ── Sign-encode helpers ──────────────────────────────────────────────────
    // is_first=1 → {~msb, msb, msb}    is_last=1 → {0,0,~msb}    else → {0,1,~msb}
    function automatic [2:0] sign_encode;
        input msb; input is_first_pp; input is_last_pp;
        sign_encode = is_first_pp ? {~msb,  msb,  msb }
                    : is_last_pp  ? {1'b0, 1'b0, ~msb }
                                  : {1'b0, 1'b1, ~msb };
    endfunction

    // is_first=1 → 3'b100    is_last=1 → 3'b001    else → 3'b011
    function automatic [2:0] sign_encode_zero;
        input is_first_pp; input is_last_pp;
        sign_encode_zero = is_first_pp ? 3'b100
                         : is_last_pp  ? 3'b001
                                       : 3'b011;
    endfunction

    // ── Per-mode partial product arrays ─────────────────────────────────────
    //   Index 0→8b  1→16b  2→32b  3→64b
    wire [2*WIDTH-1:0] pp_base [0:3];
    wire [2*WIDTH-1:0] pp_inv  [0:3];
    wire [2*WIDTH-1:0] pp_sh   [0:3];
    wire [2*WIDTH-1:0] pp_sh_i [0:3];
    wire [2*WIDTH-1:0] pp_zero [0:3];

    genvar m;
    generate
        for (m = 0; m < 4; m++) begin : gen_mode
            // W_M     : element width  (8 → 16 → 32 → 64)
            // PAD     : leading zeros so the bundle fills BW bits exactly
            //           BW - (W_M+1 data) - 3(SE) - 2(hot_ones) = BW - W_M - 6
            // SHIFT_K : div-shift exponent = log2(W_M) + 1 = m + 4
            localparam integer W_M     = 8 << m;
            localparam integer PAD     = BW - W_M - 6;
            localparam integer SHIFT_K = m + 4;

            // Sign-extended W_M-bit subword and its Booth variants
            wire [W_M:0] raw_w    = { selected_multiplicand[W_M-1] & ~is_unsigned,
                                       selected_multiplicand[W_M-1:0] };
            wire [W_M:0] raw_i_w  = ~raw_w;
            wire [W_M:0] raw_s_w  =  raw_w << 1;
            wire [W_M:0] raw_si_w =  raw_i_w << 1;

            // Sign-encoding bits for each variant
            wire [2:0] SE_b  = sign_encode     (raw_w   [W_M], is_first, is_last);
            wire [2:0] SE_i  = sign_encode     (raw_i_w [W_M], is_first, is_last);
            wire [2:0] SE_s  = sign_encode     (raw_w   [W_M], is_first, is_last);
            wire [2:0] SE_si = sign_encode     (raw_i_w [W_M], is_first, is_last);
            wire [2:0] SE_z  = sign_encode_zero(is_first, is_last);

            // shift = div * 2*W_M  +  rem * 2
            wire [31:0] shift_w = (div << SHIFT_K) + (rem << 1);

            // Pack bundle → shift into position → extract [2*WIDTH+1:2]
            wire [BW-1:0] ext_b  = { {PAD{1'b0}}, SE_b,  raw_w,             hotest_ones } << shift_w;
            wire [BW-1:0] ext_i  = { {PAD{1'b0}}, SE_i,  raw_i_w,           hotest_ones } << shift_w;
            wire [BW-1:0] ext_s  = { {PAD{1'b0}}, SE_s,  raw_s_w,           hotest_ones } << shift_w;
            wire [BW-1:0] ext_si = { {PAD{1'b0}}, SE_si, raw_si_w,          hotest_ones } << shift_w;
            wire [BW-1:0] ext_z  = { {PAD{1'b0}}, SE_z,  {(W_M+1){1'b0}},  hotest_ones } << shift_w;

            assign pp_base [m] = ext_b [2*WIDTH+1:2];
            assign pp_inv  [m] = ext_i [2*WIDTH+1:2];
            assign pp_sh   [m] = ext_s [2*WIDTH+1:2];
            assign pp_sh_i [m] = ext_si[2*WIDTH+1:2];
            assign pp_zero [m] = ext_z [2*WIDTH+1:2];
        end
    endgenerate

    // ── Stage 1: vector-mode mux ─────────────────────────────────────────────
    wire [2*WIDTH-1:0] sel_base  = pp_base [vector_mode];
    wire [2*WIDTH-1:0] sel_inv   = pp_inv  [vector_mode];
    wire [2*WIDTH-1:0] sel_sh    = pp_sh   [vector_mode];
    wire [2*WIDTH-1:0] sel_sh_i  = pp_sh_i [vector_mode];
    wire [2*WIDTH-1:0] sel_zero  = pp_zero [vector_mode];

    // ── Stage 2: Booth-select mux ────────────────────────────────────────────
    assign partial_product = selze  ? sel_zero  :
                             selp1  ? sel_base  :
                             selp2  ? sel_sh    :
                             seln1  ? sel_inv   :
                             seln2  ? sel_sh_i  :
                                      {2*WIDTH{1'b0}};  // default / error

endmodule